/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pe.unjfsc.fsi.view;

import java.awt.Dimension;

/**
 *
 * @author ander
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDatos = new javax.swing.JMenu();
        jMenuItemProveedor = new javax.swing.JMenuItem();
        jMenuItemArea = new javax.swing.JMenuItem();
        jMenuItemSeccion = new javax.swing.JMenuItem();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemFamilia = new javax.swing.JMenuItem();
        jMenuItemSubFamilia = new javax.swing.JMenuItem();
        jMenuGestion = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
        );

        jMenuDatos.setText("Datos");
        jMenuDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDatosActionPerformed(evt);
            }
        });

        jMenuItemProveedor.setText("Proveedor");
        jMenuItemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProveedorActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemProveedor);

        jMenuItemArea.setText("Area");
        jMenuItemArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAreaActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemArea);

        jMenuItemSeccion.setText("Seccion");
        jMenuItemSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSeccionActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemSeccion);

        jMenuItemCategoria.setText("Categoria");
        jMenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemCategoria);

        jMenuItemFamilia.setText("Familia");
        jMenuItemFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFamiliaActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemFamilia);

        jMenuItemSubFamilia.setText("Sub Familia");
        jMenuItemSubFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSubFamiliaActionPerformed(evt);
            }
        });
        jMenuDatos.add(jMenuItemSubFamilia);

        jMenuBar1.add(jMenuDatos);

        jMenuGestion.setText("Getion");
        jMenuBar1.add(jMenuGestion);

        jMenu1.setText("Usuario");

        jMenuItem1.setText("Usuario");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cargo");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Rol");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPaneEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProveedorActionPerformed
       JInternalProveedor objJInternalProveedor = new JInternalProveedor();
       jDesktopPaneEscritorio.add(objJInternalProveedor);
       Dimension objDimencion = jDesktopPaneEscritorio.getSize();
       Dimension objDimencionSeccion = objJInternalProveedor.getSize();
       objJInternalProveedor.setLocation((objDimencion.width - objDimencionSeccion.width)/2, (objDimencion.height - objDimencionSeccion.height)/2);
       objJInternalProveedor.show();
    }//GEN-LAST:event_jMenuItemProveedorActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaActionPerformed
       JInternalCategoria objJICategoria = new JInternalCategoria();
       jDesktopPaneEscritorio.add(objJICategoria);
       Dimension objDimencion = jDesktopPaneEscritorio.getSize();
       Dimension objDimencionSeccion = objJICategoria.getSize();
       objJICategoria.setLocation((objDimencion.width - objDimencionSeccion.width)/2, (objDimencion.height - objDimencionSeccion.height)/2);
       objJICategoria.show();
    }//GEN-LAST:event_jMenuItemCategoriaActionPerformed

    private void jMenuItemAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAreaActionPerformed
       JInternalArea objJIArea = new JInternalArea();
       jDesktopPaneEscritorio.add(objJIArea);
       Dimension objDimencion = jDesktopPaneEscritorio.getSize();
       Dimension objDimencionSeccion = objJIArea.getSize();
       objJIArea.setLocation((objDimencion.width - objDimencionSeccion.width)/2, (objDimencion.height - objDimencionSeccion.height)/2);
       objJIArea.show();
    }//GEN-LAST:event_jMenuItemAreaActionPerformed

    private void jMenuItemSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSeccionActionPerformed
       JInternalSeccion objJISeccion = new JInternalSeccion();
       jDesktopPaneEscritorio.add(objJISeccion);
       Dimension objDimencion = jDesktopPaneEscritorio.getSize();
       Dimension objDimencionSeccion = objJISeccion.getSize();
       objJISeccion.setLocation((objDimencion.width - objDimencionSeccion.width)/2, (objDimencion.height - objDimencionSeccion.height)/2);
       objJISeccion.show();
    }//GEN-LAST:event_jMenuItemSeccionActionPerformed

    private void jMenuItemFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFamiliaActionPerformed
       JInternalFamilia objJIFamilia = new JInternalFamilia();
       jDesktopPaneEscritorio.add(objJIFamilia);
       Dimension objDimencion = jDesktopPaneEscritorio.getSize();
       Dimension objDimencionSeccion = objJIFamilia.getSize();
       objJIFamilia.setLocation((objDimencion.width - objDimencionSeccion.width)/2, (objDimencion.height - objDimencionSeccion.height)/2);
       objJIFamilia.show();
    }//GEN-LAST:event_jMenuItemFamiliaActionPerformed

    private void jMenuItemSubFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSubFamiliaActionPerformed
       JInternalSubFamilia objJISubFamilia = new JInternalSubFamilia();
       jDesktopPaneEscritorio.add(objJISubFamilia);
       Dimension objDimencion = jDesktopPaneEscritorio.getSize();
       Dimension objDimencionSeccion = objJISubFamilia.getSize();
       objJISubFamilia.setLocation((objDimencion.width - objDimencionSeccion.width)/2, (objDimencion.height - objDimencionSeccion.height)/2);
       objJISubFamilia.show();
    }//GEN-LAST:event_jMenuItemSubFamiliaActionPerformed

    private void jMenuDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDatosActionPerformed

    }//GEN-LAST:event_jMenuDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuDatos;
    private javax.swing.JMenu jMenuGestion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemArea;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemFamilia;
    private javax.swing.JMenuItem jMenuItemProveedor;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSeccion;
    private javax.swing.JMenuItem jMenuItemSubFamilia;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
